In [2]:
import pandas as pd

movies_df = pd.read_csv("movies.csv")
ratings_df = pd.read_csv("ratings.csv")
users_df = pd.read_csv("users.csv")

In [3]:
movies_df

  movie_id           title    genre  release_year  is_available
0     M001   Space Journey   Sci-Fi          2020             1
1     M002   Love in Seoul  Romance          2022             1
2     M003  Laugh Out Loud   Comedy          2021             1
3     M004     Old Classic    Drama          1999             0

In [4]:
ratings_df

   rating_id user_id movie_id             rated_at  rating review_status
0      RT001    U001     M003  2026-01-01 20:00:00     4.0            OK
1      RT002    U002     M003  2026-01-01 20:00:00     5.0            OK
2      RT003    U003     M001  2026-01-01 20:00:00     4.0            OK
3      RT004    U004     M002  2026-01-01 20:00:00     3.0            OK
4      RT005    U001     M001  2026-01-02 20:00:00     5.0            OK
5      RT006    U002     M003  2026-01-02 20:00:00     4.0            OK
6      RT007    U002     M003  2026-01-02 20:00:00     5.0            OK
7      RT008    U003     M002  2026-01-02 20:00:00     2.0           BAD
8      RT009    U004     M003  2026-01-02 20:00:00     3.0       SUSPECT
9      RT010    U001     M002  2026-01-03 20:00:00     4.0            OK
10     RT011    U002     M003  2026-01-03 20:00:00     4.0            OK
11     RT012    U003     M003  2026-01-03 20:00:00     5.0            OK
12     RT013    U001     M003  2026-01-03 20:00:00     3.0       SUSPECT
13     RT014    U004     M001  2026-01-03 20:00:00     4.0            OK
14     RT015    U001     M004  2026-01-04 20:00:00     5.0            OK
15     RT016    U002     M001  2026-01-04 20:00:00     2.0            OK
16     RT017    U003     M002  2026-01-04 20:00:00     NaN            OK
17     RT018    U004     M003  2026-01-04 20:00:00     4.0            OK
18     RT019    U003     M001  2026-01-05 20:00:00     5.0            OK
19     RT020    U002     M002  2026-01-05 20:00:00     3.0       SUSPECT

In [5]:
users_df

  user_id user_name  age     city signup_date
0    U001       Kim   27    SEOUL  2025-12-01
1    U002       Lee   31    BUSAN  2025-12-05
2    U003      Park   24  INCHEON  2025-12-07
3    U004      Choi   29    SEOUL  2025-12-10

In [6]:
users_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      4 non-null      object
 1   user_name    4 non-null      object
 2   age          4 non-null      int64
 3   city         4 non-null      object
 4   signup_date  4 non-null      object
dtypes: int64(1), object(4)
memory usage: 292.0+ bytes

In [15]:
def is_bad(review_status, rating):
    if review_status == "BAD":
        return True
    elif rating is None :
        return True
    else:
        return False


print(is_bad("OK",4))
print(is_bad("BAD",5))
print(is_bad("OK",None))

False
True
True

In [43]:
def sum_ignore_none(values):
    nums = 0
    for i in values:
        if i is None :
            continue
        nums += i
    return nums

print(sum_ignore_none([1, None, 5]))

6

In [21]:
import pandas as pd

movies_df = pd.read_csv("movies.csv")
ratings_df = pd.read_csv("ratings.csv", parse_dates=["rated_at"])
users_df = pd.read_csv("users.csv")

print(users_df.shape)
print(movies_df.shape)
print(ratings_df.shape)
print(ratings_df.head(2))

(4, 5)
(4, 5)
(20, 6)
  rating_id user_id movie_id            rated_at  rating review_status
0     RT001    U001     M003 2026-01-01 20:00:00     4.0            OK
1     RT002    U002     M003 2026-01-01 20:00:00     5.0            OK

In [40]:
from altair.datasets._readimpl import is_available
# Q13

import pandas as pd

movies_df = pd.read_csv("movies.csv")
ratings_df = pd.read_csv("ratings.csv", parse_dates=["rated_at"])
users_df = pd.read_csv("users.csv")

dub_cnt = ratings_df.duplicated(subset=["user_id", "movie_id", "rated_at"]).sum()
print(f"dub_cnt : {dub_cnt}")
df_dropdup = ratings_df.drop_duplicates(subset=["user_id", "movie_id", "rated_at"], keep="first")
df_dropdup["rating_num"] = pd.to_numeric(df_dropdup["rating"], errors="coerce")
merged1 = df_dropdup.merge(movies_df, how='left', on = "movie_id")
merged1 = merged1.merge(users_df, how = 'left', on = "user_id")
df_clean = merged1[is_available == 1]
df_clean

dub_cnt : 1

C:\Users\gorhk\AppData\Local\Temp\ipykernel_73484\2421548105.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropdup["rating_num"] = pd.to_numeric(df_dropdup["rating"], errors="coerce")

KeyError: False

In [ ]:
import pandas as pd

ratings_df = pd.read_csv("ratings.csv", parse_dates=["rated_at"])